/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DIR_H_RPCGEN
#define _DIR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define READDIR_PROG 0x20000001
#define READDIR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define READDIR_PROC 1
extern  char ** readdir_proc_1(char **, CLIENT *);
extern  char ** readdir_proc_1_svc(char **, struct svc_req *);
extern int readdir_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define READDIR_PROC 1
extern  char ** readdir_proc_1();
extern  char ** readdir_proc_1_svc();
extern int readdir_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DIR_H_RPCGEN */
