DROP SCHEMA IF EXISTS flasklearning;
CREATE SCHEMA IF NOT EXISTS flasklearning;

USE flasklearning;

CREATE TABLE user (
	user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE, 
    pass VARCHAR(1000) NOT NULL
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

